---
title: "Mini-Project 2"
author: "Sneha, Pema, Tenzin"
date: "October 31, 2017"
output: html_document
---


## Loading the data


```{r, include=FALSE, message=FALSE}
load("house_elections.rda")
load("candidates.rda")
load("committees.rda")
load("contributions.rda")
```

```{r, message=FALSE}
library(tidyverse)
library(lubridate)
```
```{r}
head(house_elections)
```

```{r}
head(committees)
```
```{r}
head(candidates)
```
```{r}
head(contributions)
```

```{r}
candidate_contributions <- candidates %>%
  #joining candidates and contributions by "cand_id"
  inner_join(contributions, by = "cand_id") %>%
  #selecting the relevant variables
  select(cand_id, cand_name, cand_ici, cand_election_yr, cand_party_affiliation, cmte_id, transaction_type, name, transaction_dt, transaction_amt)
head(candidate_contributions)
```

```{r}
committee_to_cand <- candidate_contributions %>%
  #joining candidates, committees and contributions
  inner_join(committees, by = "cmte_id") %>%
  #select relevant columns
  select(cmte_id, cmte_name, cmte_party_affiliation, transaction_type, name, transaction_dt, transaction_amt, cand_id.y, cand_name, cand_election_yr, cand_party_affiliation, cand_ici)
head(committee_to_cand)
#view dimensions of the new tbl_dr
dim(committee_to_cand)
```
```{r}
#set the desired values of transaction_type
transaction <- c("24A", "24E")
committee_to_cand <- committee_to_cand %>%
  #filter transaction_type to values in 'transaction' i.e either "24A" or "24E"
  filter(transaction_type %in% transaction) %>%
  mutate(transaction_dt = mdy(transaction_dt)) %>%
  #groups data by committee name
  group_by(cmte_name)
head(committee_to_cand)
#view dimensions to ensure there is enough data to use in our anaysis
dim(committee_to_cand)

```
```{r}
glimpse(committee_to_cand)
```






